added xarm robot
ros-infrastructure/robots.ros.org pull request #205
Opened 2020-07-29 11:02 UTC by DanielWang123321

added xarm robot
(2020/07/29)

2020-09-10 09:17 UTC, tfoote requested changes

2020-09-10 09:17 UTC, tfoote commented on _posts/2020-07-29-xarm.md
> +
Please add at least a sentence or two overview.

2020-09-10 09:17 UTC, tfoote commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
This and all the other .idea folder files should be removed from the PR

2020-09-15 11:40 UTC, DanielWang123321 reviewed
modified, thanks.

2020-09-15 11:40 UTC, DanielWang123321 commented on _posts/2020-07-29-xarm.md
> +
ok, done. thanks.

2020-09-15 11:41 UTC, DanielWang123321 commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
deleted

2020-09-22 20:30 UTC, tfoote approved these changes

2020-09-22 20:30 UTC, merged