Adding new robot by MIP robotics the MIP junior 300
ros-infrastructure/robots.ros.org pull request #207
Opened 2020-09-01 10:10 UTC by MIP-robotics

Hello,

I hope this new robot can be added to the ROs robot store.

Thank you,
MIP robotics

2020-09-10 09:12 UTC, tfoote requested changes

2020-09-10 09:12 UTC, tfoote commented on _posts/2020-08-28-mip-robotics-junior-300.md
> +wiki_homepage: https://github.com/MIPRobotics/ROS_robotics_simulation
This should be a link to a page on the ROS wiki with developer documentation for how to use the robot with the ROS interface. https://github.com/ros-infrastructure/robots.ros.org/blob/gh-pages/contributing.md#what-content-should-be-on-the-site

The page that this currently links to has no content beyond the title.

2020-09-10 09:50 UTC, MIP-robotics commented on _posts/2020-08-28-mip-robotics-junior-300.md
> +wiki_homepage: https://github.com/MIPRobotics/ROS_robotics_simulation
Yes, this repo will have the instructions. 
Currently, only the scaffolding was generated. 
We expect the repo to be full by end of next week.

2020-09-22 20:35 UTC, tfoote commented on _posts/2020-08-28-mip-robotics-junior-300.md
> +wiki_homepage: https://github.com/MIPRobotics/ROS_robotics_simulation
Please read the instructions. They specifically talk about having a ROS wiki page with the developer overview about how to get up and running. This helps with discovery through a consistent user experience. The wiki page can point to more detailed documentation on github or elsewhere. 

Please note that the link you provide to the bare repo doesn't have any documentation, you have to click into other files to find any significant documentation.

2020-09-28 09:29 UTC, MIP-robotics commented on _posts/2020-08-28-mip-robotics-junior-300.md
> +wiki_homepage: https://github.com/MIPRobotics/ROS_robotics_simulation
Wiki created and link updated

2020-10-06 08:53 UTC, tfoote commented
Please either embed the installation instructions in the wiki page or link directly to them. You have only one link that takes you to a top level of the repository with a Readme that has no links to developer documentation. The user is required to then go browsing through various readme files to find the right ones. YOu should at least link to the installation docs and the operations documents.

2020-10-09 00:36 UTC, tfoote approved these changes
Thanks for filling that in. I made the link on the wiki a little bit clearer too.

2020-10-09 00:37 UTC, merged