Adding EvaMars Robot
ros-infrastructure/robots.ros.org pull request #212
Opened 2020-12-09 07:49 UTC by Akerdogmus

2021-01-12 08:42 UTC, tfoote requested changes
Upon reading the documentation this appears to be a virtual robot model and not a hardware robot. 

That's not something that we've been intending to capture here right now as I don't think it fits into any of the existing categories because it's not a substitute for other things in the categories. So I would suggest that instead of posting it here that you make an announcement of this in the ROS Projects category on ROS Discourse https://discourse.ros.org/c/ros-projects/10

2021-01-12 08:42 UTC, tfoote commented on _posts/2020-12-09-evamars.md
> +wiki_homepage: http://wiki.ros.org/Robots/EvaMars
This wiki page doesn't appear to exist.

2021-01-12 10:27 UTC, Akerdogmus commented on _posts/2020-12-09-evamars.md
> +wiki_homepage: http://wiki.ros.org/Robots/EvaMars
We will consider your suggestion. Since we were working on creating an example of educational robots in this style, we thought these robots could be seen on the ROS Wiki. As far as I understand, we can only add robots produced as hardware for the "Robots" section.

2021-01-14 08:47 UTC, Akerdogmus commented
I think there was a misunderstanding. The document I sent must have a hardware picture of the robot. So the robot is available both in hardware and virtually.

2021-01-23 02:11 UTC, tfoote commented
Please create the wiki page I commented on. And similarly where is documentation of the robot itself? There appears to only be documentation of the software stack to use the robot and that only has renderings of the simulated robot which is why I didn't realize that there's a real robot. Where can I go to get specifications of the robot and who's selling or distributing the robot?

2021-11-05 23:53 UTC, tfoote commented
Closing due to no response in almost a year.

2021-11-05 23:53 UTC, closed without merging