Updated info about Robotnik robots
ros-infrastructure/robots.ros.org pull request #213
Opened 2020-12-09 12:45 UTC by amartinez96

All the information was updated about all the new Robotnik robots. We also deleted the ones that are not produced anymore

2021-01-12 08:36 UTC, tfoote requested changes
Thanks for the update. One small formatting change requested.

2021-01-12 08:36 UTC, tfoote commented on assets/css/main.css
> +html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}a
Please remove this diff from the changelog.

2021-01-12 13:30 UTC, amartinez96 commented on assets/css/main.css
> +html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}a
Solved with the next commit, thanks

2021-01-23 02:11 UTC, tfoote approved these changes

2021-01-23 02:11 UTC, merged