Niryo ned
ros-infrastructure/robots.ros.org pull request #220
Opened 2021-02-15 14:03 UTC by Pauline-Odet

I added to ros robots the new Niryo Robot, Ned

2021-02-17 07:25 UTC, tfoote requested changes
This looks like a nicely layed out page. However I noticed that the wiki homepage linked for the robot does not appear to exist. That should have the ROS API documentation and instructions for how to integrate with the robot.

2021-02-17 07:25 UTC, tfoote commented on _posts/2021-02-15-niryo-ned.md
> +wiki_homepage: http://wiki.ros.org/niryo_ned
This wiki page does not appear to exist.

2021-02-17 11:44 UTC, Pauline-Odet commented on _posts/2021-02-15-niryo-ned.md
> +wiki_homepage: http://wiki.ros.org/niryo_ned
Thank you for your answer !
 Actually, we just created the wiki page and it has not been accepted yet. 
I'll let you know when the wiki page is online !

2021-03-01 11:15 UTC, Pauline-Odet commented on _posts/2021-02-15-niryo-ned.md
> +wiki_homepage: http://wiki.ros.org/niryo_ned
Hi @tfoote, I just updated the wiki homepage, which is now online ! My fork is ready to be merged now

2021-03-03 01:24 UTC, tfoote approved these changes
Thanks for iterating. Note that to follow our naming convention I moved your page to Robots/ned not just ned at the top.

2021-03-03 01:24 UTC, tfoote commented on _posts/2021-02-15-niryo-ned.md
> +wiki_homepage: http://wiki.ros.org/ned
```suggestion
wiki_homepage: http://wiki.ros.org/Robots/ned
```
Fixing url to follow our standards for wiki page naming.

2021-03-03 01:25 UTC, merged