add the Agilex LIMO into support
ros-infrastructure/robots.ros.org pull request #237
Opened 2021-12-10 06:40 UTC by agilexrobotics

2021-12-13 23:42 UTC, tfoote requested changes
Please take a moment to fill in the main body and fix the icon size. The icon needs to be small to be able to fit onto the card. 

There's some guidelines to help guide contributions here: https://robots.ros.org/contributing/

2021-12-13 23:42 UTC, tfoote commented on _posts/2021-12-10-limo.md
> +icon: /assets/img/robots/limo/limo.jpg
Please make the icon 80x80 pixels. You can embed the additional picture in the main body. See the comment on the TODO lower.

2021-12-13 23:42 UTC, tfoote commented on _posts/2021-12-10-limo.md
> +TODO Fill in the long description/article here.
The content for this page is just at TODO. It needs more information. I'd recommend some descriptions possibly some images and some video embeds for the best engagement.

2021-12-20 03:27 UTC, agilexrobotics reviewed
update image

2021-12-20 03:29 UTC, agilexrobotics commented on _posts/2021-12-10-limo.md
> +icon: /assets/img/robots/limo/limo.jpg
the new image i have push to the laster version

2021-12-20 03:30 UTC, agilexrobotics commented on _posts/2021-12-10-limo.md
> +TODO Fill in the long description/article here.
New veison i have add the description into the md file

2021-12-29 14:04 UTC, tfoote approved these changes
Thanks for the updates.

2021-12-29 14:04 UTC, merged