add robot:mecharm-270
ros-infrastructure/robots.ros.org pull request #258
Opened 2022-07-28 08:54 UTC by anla-xu

add robot:mecharm-270

2022-07-28 23:16 UTC, tfoote requested changes
Please provide a link to the developer documentation. 

I'd also suggest filling in a little bit more multimedia content or links to your description but that's not necessary.

2022-07-28 23:16 UTC, tfoote commented on _posts/2022-07-28-mecharm-270.md
> +wiki_homepage: https://www.elephantrobotics.com/en/mecharm-cn/
This link should contain the ROS developer documentation for how to use the robot and not the product website. (Unless the docs are on the main website. But I don't find them there.)

2022-08-01 08:46 UTC, anla-xu commented
A ros introduction URL has been changed, is it possible?

2022-08-15 22:04 UTC, tfoote approved these changes
Thanks for the update. That will work.

I still recommend slightly more graphically rich content but that's not a gating factor.

2022-08-15 22:04 UTC, merged