Add MD80 product page
ros-infrastructure/robots.ros.org pull request #260
Opened 2022-09-06 06:34 UTC by mabrobotics

2022-09-08 18:23 UTC, tfoote requested changes
The icon should be 80x80: https://robots.ros.org/contributing/

Please make sure to make a wiki page with the developer documentation.

2022-09-08 18:23 UTC, tfoote commented on _posts/2022-08-05-md80.md
> +wiki_homepage:
This is a required field which should link to a page with the ROS developer documentation.

2022-09-21 06:41 UTC, mabrobotics commented on _posts/2022-08-05-md80.md
> +wiki_homepage:
How can we set up a wiki page? We cannot find any create page button, apart from the create my homepage button in our profile (not sure if homepage should be about the product though)

2022-10-11 23:13 UTC, tfoote approved these changes
Thanks for filling in the wiki content.

2022-10-11 23:14 UTC, merged