Add amiga robot to robots.ros.org
ros-infrastructure/robots.ros.org pull request #274
Opened 2023-05-26 16:50 UTC by jerrycowell96

2023-06-09 15:53 UTC, jerrycowell96 commented
@tfoote can you please review and merge this branch?

2023-06-09 16:29 UTC, tfoote requested changes
Thanks for submitting this. I have two pieces of feedback. With those resolved it looks good.

2023-06-09 16:29 UTC, tfoote commented on _posts/2023-05-26-farm-ng-amiga.md
> +wiki_homepage: https://farm-ng.com/pages/for-research
This doesn't appear to have any ROS API documentation. Please use the ROS interface link below in the description.

2023-06-09 16:29 UTC, tfoote commented on _posts/2023-05-26-farm-ng-amiga.md
> +icon: /assets/img/robots/farm-ng-amiga/amiga.png
This is the same as the full size image. It should be smaller following that icon sizing guide for the tile layout.

2023-06-09 16:42 UTC, jerrycowell96 commented
@tfoote Thank you for your review. You will find these changes there and the conflicts resolved.

2023-06-09 21:00 UTC, tfoote requested changes
Thanks for iterating. That's good progress, but neither really meet our needs for contributing. 

Please read through: https://robots.ros.org/contributing/ for more details.

2023-06-09 21:00 UTC, tfoote commented on _posts/2023-05-26-farm-ng-amiga.md
> +wiki_homepage: http://wiki.ros.org/Robots/farm-ng-amiga
The link is now following our usual pattern, but there doesn't appear to be any content here: http://wiki.ros.org/Robots/farm-ng-amiga which should tell developers about the ROS API.

2023-06-09 21:00 UTC, tfoote commented on _posts/2023-05-26-farm-ng-amiga.md
> +icon: /assets/img/robots/farm-ng-amiga/farm-ng-logo.png
This icon should be 80x80 picture of the robot which is what people will see in the list of the robots.

2023-06-09 22:15 UTC, jerrycowell96 commented
Oh my apologies. I did not understand at first but I'll make those changes immediately. Thank you.

2023-06-16 17:30 UTC, jerrycowell96 commented
@tfoote Hi, I have resolved the above conflicts. Can you please review this PR and approve. If you have any other suggestions or question please do not hesitate to let me know.

2023-06-16 21:13 UTC, tfoote requested changes
One small change. It looks like you tweaked the test script while working and included it in the PR. 

Thanks for filling out the wiki page.

2023-06-16 21:13 UTC, tfoote commented on test_site.bash
> +ghrocker --config _config.yml -- .
This looks like an unrelated change that got pulled in.

2023-06-16 21:14 UTC, jerrycowell96 commented on test_site.bash
> +ghrocker --config _config.yml -- .
Yikes okay i'll change that right now.

2023-06-16 21:17 UTC, jerrycowell96 commented on test_site.bash
> +ghrocker --config _config.yml -- .
Should be reverted back to original. Let me know if anything else comes up.

2023-06-16 21:28 UTC, tfoote approved these changes

2023-06-16 21:28 UTC, merged

2023-06-16 21:29 UTC, tfoote commented
Thanks for the iteration. it should go live shortly.