add the Niryo Ned2 to the robots list
ros-infrastructure/robots.ros.org pull request #278
Opened 2023-06-26 10:15 UTC by jmottier-niryo

2023-06-26 14:38 UTC, tfoote requested changes
Please add links to ROS interface documentation.

2023-06-26 14:38 UTC, tfoote commented on _posts/2023-04-06-ned2.md
> +wiki_homepage:
Please add a link to ROS developer documentation here.

2023-07-19 10:06 UTC, jmottier-niryo commented on _posts/2023-04-06-ned2.md
> +wiki_homepage:
Issue resolved with the commit bf7a2f2faf6e75e285ef8eed26220f9046ab1615

2023-08-28 08:03 UTC, jmottier-niryo commented
@tfoote I allow myself to tag you in case you missed this pull request update

2023-08-31 17:13 UTC, tfoote approved these changes
Thanks for the ping, please do that after making an update. Reviewers don't get a notification when new changes are pushed. 

The new link looks good.

2023-08-31 17:13 UTC, merged