机械臂资料添加
ros-infrastructure/robots.ros.org pull request #287
Opened 2024-04-16 02:02 UTC by pengziliang

2024-06-21 09:29 UTC, tfoote requested changes
The changes look fine from reading. Do you know why this isn't running the CI actions?

2024-06-21 09:29 UTC, tfoote commented on _posts/2024-04-09-myAGV.md
> +wiki_homepage: http://wiki.ros.org/Robots/myAGV
Please point the wiki_homepage to a link where there's ROS developer documentation on how to interface to the devices. For this and all below. I only checked a few that didn't seem to exist on the wiki as currently linked.

2024-11-18 08:20 UTC, pengziliang commented on _posts/2024-04-09-myAGV.md
> +wiki_homepage: http://wiki.ros.org/Robots/myAGV
Hello, what issue are you encountering? Is it that the wiki_homepage link cannot be redirected?

2024-11-19 22:03 UTC, tfoote commented on _posts/2024-04-09-myAGV.md
> +wiki_homepage: http://wiki.ros.org/Robots/myAGV
That link: http://wiki.ros.org/Robots/myAGV has no content. 

![image](https://github.com/user-attachments/assets/ac58d854-9850-42b1-8e1b-250b4025d05d)

2024-11-19 22:05 UTC, tfoote commented on _posts/2024-04-09-myAGV.md
> +wiki_homepage: http://wiki.ros.org/Robots/myAGV
I see you've fixed the links now. Closing this

2024-11-19 22:06 UTC, tfoote approved these changes
Thanks for the updates. It's now passing CI too.

2024-11-19 22:06 UTC, merged